# Unzip the data

In [1]:
## Unzip the data
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw")

# Core Data Structures

Pandas has two primary data structures:

- Series: Think of this as a single column in Excel. It is 1-dimensional (just a list of items), but unlike a standard Python list, every item has a specific label (called an Index).

- DataFrame: Think of this as the entire spreadsheet. It is 2-dimensional (rows and columns). A DataFrame is essentially just multiple Series joined together.

In [3]:
# Series Example
import pandas as pd

s = pd.Series([10, 20, 30, 40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
# DataFrame Example
data = {
    "customer": ["Anna", "David", "Liza"],
    "revenue": [100, 250, 180]
}

df = pd.DataFrame(data)
df

  customer  revenue
0     Anna      100
1    David      250
2     Liza      180

## Importing orders.csv file

In [33]:
import pandas as pd

df_orders = pd.read_csv("../data/raw/orders.csv")
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

## Importing products.csv file

In [34]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

## Common parameters

In [ ]:
pd.read_csv(
    "{data/sales.csv}",
    sep=",",
    header=0,
    na_values=["NA", ""],
    parse_dates=["order_date"]
)

# Exploring Data with Pandas
## Top N rows of the data

In [35]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [36]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [37]:
df_products.tail()

,product_id,product_name,aisle_id,department_id,prices
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.3
49689,49685,En Croute Roast Hazelnut Cranberry,42,1,3.1
49690,49686,Artisan Baguette,112,3,7.8
49691,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,4.7
49692,49688,Fresh Foaming Cleanser,73,11,13.5

In [38]:
df_orders.tail()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

## Column names of the DataFrame

In [39]:
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [40]:
df_products.columns

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'prices'], dtype='str')

## Data types of the columns

In [41]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [43]:
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 49693 entries, 0 to 49692
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49693 non-null  int64
 1   product_name   49677 non-null  str
 2   aisle_id       49693 non-null  int64
 3   department_id  49693 non-null  int64
 4   prices         49693 non-null  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.9 MB

## Summary statistics of the data

In [44]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [45]:
df_products.describe()

         product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24844.345139     67.770249      11.728433      9.994136
std    14343.717401     38.316774       5.850282    453.519686
min        1.000000      1.000000       1.000000      1.000000
25%    12423.000000     35.000000       7.000000      4.100000
50%    24845.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000  99999.000000

# Data Wrangling and Subsetting
## Data Wrangling Procedures
### Dropping columns

In [46]:
# option 1 
df_orders_new = df_orders.drop(columns=["eval_set"])
df_orders_new

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0
...,...,...,...,...,...,...
3421078,2266710,206209,10,5,18,29.0
3421079,1854736,206209,11,4,10,30.0
3421080,626363,206209,12,1,12,18.0
3421081,2977660,206209,13,1,12,7.0
3421082,272231,206209,14,6,14,30.0

In [47]:
# option 2
df_orders.drop(columns = ['eval_set'])

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0
...,...,...,...,...,...,...
3421078,2266710,206209,10,5,18,29.0
3421079,1854736,206209,11,4,10,30.0
3421080,626363,206209,12,1,12,18.0
3421081,2977660,206209,13,1,12,7.0
3421082,272231,206209,14,6,14,30.0

In [48]:
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [36]:
# in case if you want to make the changes in main data also
# df_orders.drop(columns = ['eval_set'], inplace=True)

# df_orders.head()

### Renaming columns

In [49]:
# To rename the eval_set column to dataset_type in your orders.csv dataframe, the full function would be:

# option 1 :
df_orders_new = df_orders.rename(columns={"eval_set": "dataset_type"})
df_orders_new.head()

,order_id,user_id,dataset_type,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [50]:
# option 2 :
df_orders.rename(columns = {'eval_set' : 'dataset_type'})

,order_id,user_id,dataset_type,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [51]:
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

* By doing this, it will not change the original DataFrame df_orders. If you want to change the original DataFrame, you can either assign the result back to the original DataFrame or use the inplace=True parameter.

In [ ]:
# df_orders.rename(columns = {'eval_set': 'dataset_type'}, inplace=True)

# df_orders.head()

### Changing data types

In [53]:
# To change the order_id column to integer type in your orders.csv dataframe, the full function would be:
# Option 1:
df_orders_new = df_orders.astype({"order_id": "int64"})

In [54]:
# option 2:
df_orders.astype({'order_id': 'int64'})

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [25]:
df_orders.dtypes

order_id                    int64
user_id                     int64
eval_set                      str
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

* By doing this, it will not change the original DataFrame df_orders. If you want to change the original DataFrame, you can either assign the result back to the original DataFrame or overwrite the column directly.

In [32]:
#df_orders['order_id'] = df_orders['order_id'].astype('int64')

#df_orders.dtypes

### Transforming data (e.g., creating new columns, applying functions to columns)

Create a new DataFrame with transformed data

In [58]:
# OPTION 1:
df_orders_new = df_orders.assign(
    is_weekend = df_orders["order_dow"].isin([0, 6]),
    is_morning = df_orders["order_hour_of_day"] < 12
)

In [56]:
#OPTION 2:
df_orders["is_weekend"] = df_orders["order_dow"].isin([0, 6])
df_orders["is_morning"] = df_orders["order_hour_of_day"] < 12

df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,is_weekend,is_morning
0,2539329,1,prior,1,2,8,NaN,False,True
1,2398795,1,prior,2,3,7,15.0,False,True
2,473747,1,prior,3,3,12,21.0,False,False
3,2254736,1,prior,4,4,7,29.0,False,True
4,431534,1,prior,5,4,15,28.0,False,False

Creating an order frequency category based on order_number

In [59]:
df_orders["order_frequency_category"] = df_orders["order_number"].apply(
    lambda x: "New" if x == 1 
    else "Low" if x <= 5 
    else "High"
)

df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,is_weekend,is_morning,order_frequency_category
0,2539329,1,prior,1,2,8,NaN,False,True,New
1,2398795,1,prior,2,3,7,15.0,False,True,Low
2,473747,1,prior,3,3,12,21.0,False,False,Low
3,2254736,1,prior,4,4,7,29.0,False,True,Low
4,431534,1,prior,5,4,15,28.0,False,False,Low

Handling missing values in days_since_prior_order

In [60]:
df_orders["days_since_prior_order"] = df_orders["days_since_prior_order"].fillna(0)

df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,is_weekend,is_morning,order_frequency_category
0,2539329,1,prior,1,2,8,0.0,False,True,New
1,2398795,1,prior,2,3,7,15.0,False,True,Low
2,473747,1,prior,3,3,12,21.0,False,False,Low
3,2254736,1,prior,4,4,7,29.0,False,True,Low
4,431534,1,prior,5,4,15,28.0,False,False,Low

Creating time-of-day buckets

In [61]:
df_orders["time_bucket"] = df_orders["order_hour_of_day"].apply(
    lambda x: "Morning" if 6 <= x < 12
    else "Afternoon" if 12 <= x < 18
    else "Evening"
)

df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,is_weekend,is_morning,order_frequency_category,time_bucket
0,2539329,1,prior,1,2,8,0.0,False,True,New,Morning
1,2398795,1,prior,2,3,7,15.0,False,True,Low,Morning
2,473747,1,prior,3,3,12,21.0,False,False,Low,Afternoon
3,2254736,1,prior,4,4,7,29.0,False,True,Low,Morning
4,431534,1,prior,5,4,15,28.0,False,False,Low,Afternoon

### Transponsing a DateFrame

In [62]:
df_departments = pd.read_csv("../data/raw/departments.csv")
df_departments.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [63]:
df_departments.T

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [ ]:
# The Flip
# This flips the rows and columns.If your departments were columns,they are now rows.

df_dep_t = df_departments.T

In [ ]:
# Bringing the Labels into the Table
# By default, the old column names are stuck in the "Index" (the far left margin). 
# This command pushes them into the actual data area so we can work with them.
df_dep_t.reset_index(inplace=True)

In [72]:
# Grabbing the New Headers
# We take the very first row of the data (iloc[0]) and save it into a variable. 
# We intend for this row to become the names of our columns.
new_header = df_dep_t.iloc[0]

In [73]:
# Trimming the Data
# Since the first row is now saved as our "header," we don't want it duplicated inside the table. 
# This line creates a new DataFrame that starts from the second row (1:) onwards.
df_dep_t_new = df_dep_t[1:]

In [74]:
# Assigning the Names
# Finally, we tell Pandas: "Use the values we saved in new_header as the official titles for the columns."
df_dep_t_new.columns = new_header   

df_dep_t_new.head()

0 department_id department
1             1     frozen
2             2      other
3             3     bakery
4             4    produce
5             5    alcohol

Why go through all this trouble?

In datasets like the one you're using, "Departments" might be stored as a single horizontal row. To join this data with your orders DataFrame, you need "Department" to be a vertical column so Pandas can match the IDs.

# Exporting the data

## Exprting to CSV

In [76]:
df_orders.to_csv("../data/processed/orders_cleaned.csv", index=False)

In [77]:
df_products.to_csv("../data/processed/products_cleaned.csv", index=False)

In [78]:
df_dep_t_new.to_csv("../data/processed/departments_t.csv", index=False)

# Understanding Relative Paths in Python

The most practical "life skills" in programming: 

File Paths. Understanding this is what ensures your code works on your computer, your friend's computer, and the cloud without breaking.

A file path is just a set of directions. Here is the breakdown of the two types mentioned:

1. Absolute Path (The "Full Address")
This is the equivalent of a full mailing address, including the city, state, and zip code. It starts from the very "root" of your hard drive.

Example: C:/Users/YourName/Project/data/file.xlsx

The Problem: If you send this code to a teammate, it will crash. Why? Because their computer doesn't have a user named "YourName." Absolute paths are rigid and "fragile."

2. Relative Path (The "Directions from Here")
This is like telling someone, "Go down the hall and take the first door on the right." It only works if you both start in the same place (the Current Working Directory).

Example: data/file.xlsx

The Benefit: This is portable. As long as your teammate has the same project folder structure as you, the code will work perfectly for them. This is the "industry standard" for collaborative projects.

3. How to "Navigate" with Relative Paths
You’ll often see special symbols in relative paths that help you move through folders:

./ : Means "Look in the current folder."

../ : Means "Go up one folder" (the parent directory).

Real Example:

In previous step, the used path for exporting data:
"../data/processed/orders_cleaned.csv"

This tells Python:

../ : Go out of the current folder where my Jupyter Notebook is.

data/ : Look for a folder called "data."

processed/ : Look for a folder inside that called "processed."

orders_cleaned.csv : Save the file here.

## Option A

### The os.path

Windows uses backslashes (\) for paths, while Mac and Linux use forward slashes (/). 

If you hardcode your paths with /, your code might crash on a teammate's Windows machine.

os.path.join() solves this. It detects which computer you are using and automatically puts the correct slashes in between your folders.

In [79]:
import os

# Get current working directory
print("Current working directory:", os.getcwd())

# Join a relative path
file_path = os.path.join("data", "file.xlsx")
print("Relative path:", file_path)

Current working directory: c:\ACA\data_analytics_with_python\notebooks
Relative path: data\file.xlsx

Finding Your "Home Base"

os.getcwd() stands for Get Current Working Directory.
When you run this in a Jupyter Notebook, it tells you exactly where the computer thinks it is sitting. 
This is vital for debugging! If your file won't load, run this command to see if you are actually in the folder you think you're in.

If you are working inside main.ipynb (which is in the scripts or notebooks folder) and you want to open sample.xlsx (which is in the data folder), you have to tell Python to:

Leave the current room: .. (This takes you up to the main project/ folder).

Go into a new room: data/

Find the file: sample.xlsx

Final Path: ../data/sample.xlsx

## Option B

### pathlib is the "Modern Pro" Choice

In [ ]:
import pandas as pd
from pathlib import Path

# Define relative path to the data folder from scripts/
file_path = Path("../data") / "sample.csv"

# Read the CSV file
df = pd.read_csv(file_path)

# Display the first few rows
print(df.head())

The Magic Forward Slash (/):

Notice this line: file_path = Path("../data") / "sample.csv"

In standard Python, you can't divide two pieces of text.

But with pathlib, the / acts as a "Joiner." 

It automatically handles the folder slashes for you, making the code very readable and cross-platform (Windows, Mac, and Linux).