# Arithmetic Operations

In [ ]:
r = 100    # revenue
t = 0.2    # tax 

total = r * (1 + t)   #  total revenue including tax
total

120.0

In [2]:
100 > 50       #Greater Than (>)
100 == 50      #Equal To (==)
100 != 50      #Not Equal To (!=)

True

In [3]:
print((100 > 50) and (20 < 30))

True

# Basic Data Structures

## List [ ]

In [ ]:
sales = [100, 200, 150, 200]
sales

[100, 200, 150, 200]

In [ ]:
sales[0]   # gets the FIRST item → 100
sales[-1]  # gets the LAST item → 200

200

Indexing starts at 0 in Python.

Negative index -1 means start from the end.

Both returned 200 because sales[0]=100 was not printed, only sales[-1]=200 was shown.

In [10]:
sales.append(300)   # adds 300 to the END of the list
sales[1] = 250      # changes index 1 (was 200) to 250
sales

[100, 250, 150, 200, 300, 300]

In [ ]:
len(sales)   # counts how many items → 6

6

In [ ]:
total = 0               #This creates a variable to act as a "bucket" to hold our sum. We start at zero.
for value in sales:     #This tells the computer to look at the list called sales and pick up each number one by one.
    total += value      #This is a shortcut for Reassignment."Take the current total,add the new value to it,and put the result back into total"

total

1300

## Tuple ( )

Tuple is a specific way of grouping data together in Python.

While it looks similar to a standard list, it has one superpower: immutability.

A tuple is a collection of items that are ordered and unchangeable. 

In code, you recognize them because they use parentheses () instead of square brackets [].

coordinates = (40.18, 44.51)  This stores two floating-point numbers together as a single unit (likely Latitude and Longitude).

* Core Properties
  - Ordered: The items stay in the exact sequence you put them in.
  - Indexed: You can grab specific items by their position (e.g., "Give me the first item in the tuple").
  - Immutable: This is the big one. Once a tuple is created, you cannot change, add, or remove items. It is "carved in stone."

In [13]:
coordinates = (40.18, 44.51)
coordinates

(40.18, 44.51)

## Set { }

Set is a collection data structure that behaves very differently from lists or tuples.
 
Its main purpose is to handle unique data and perform mathematical logic.
* Unlike a list, a set doesn't care about the sequence. 
  If you print a set, the items might come out in a different order than you typed them.
* Because there is no fixed order, you cannot ask for "the first item" in a set.

In [14]:
customer_ids = {1, 2, 3, 3, 4}
customer_ids

{1, 2, 3, 4}

### Key Properties (The "Rules")

* Unordered: There is no "first" or "last" item. Because of this, you can't use an index (like s1[0]) to grab a value.
* Unique values only: If you try to add 2 to a set that already has a 2, nothing happens. It's self-cleaning.
* Mutable container: Even though the items inside must be unchangeable (hashable), the set itself can grow or shrink as you add or remove elements.
* Fast membership checking: This is the set's "killer feature." Because it uses hashing, checking if an item exists (x in set) is nearly instantaneous, regardless of whether the set has 10 items or 10 million.

### Creating Sets

In [18]:
s1 = {1, 2, 3}   # creating
s1

{1, 2, 3}

In [ ]:
s1 = {1, 2, 2, 3}   # creating + cleaning
s1

{1, 2, 3}

You are telling Python directly to create a set containing those specific numbers.
 
It is slightly faster because Python sees the curly braces and knows exactly what to do immediately.

In [ ]:
s2 = set([1, 2, 2, 3])  # create a set from a list by cleaning it
s2

{1, 2, 3}

You are calling the set() function. To do this, you first created a list ([1, 2, 2, 3]) and then asked Python to convert that list into a set. This is a two-step process.

* Use { } when you already know the data you want to put in the set. It’s cleaner and more "Pythonic."
* Use set() when you have an existing collection (like a list or a tuple) that you want to transform into a set—usually to remove duplicates or to make membership testing faster.

### Basic Operations

#### 1- Handling Elements (The "Editing" Tools)

Since sets are mutable, you can modify them after they are created using these specific commands:

In [22]:
s = {1, 2, 3}

In [24]:
s.add(4)        # Add element
s

{1, 2, 3, 4}

In [25]:
s.remove(2)     # Remove element (error if not found)
s

{1, 3, 4}

In [ ]:
# This is the "safe" version of remove. 
# It tries to delete 10, but if 10 isn't there, it just stays quiet and does nothing instead of crashing.
s.discard(10)   # Safe remove (no error)
s

{1, 3, 4}

In [27]:
s.pop()         # Remove random element
s

{3, 4}

In [28]:
s.pop()         # Remove random element
s

{4}

#### 2-Membership Check (The "Question" Tools)

This is where sets shine. Using the in keyword, you can instantly check if a piece of data exists within the collection.

In [ ]:
3 in s   # True/false test

False

In [30]:
4 in s # True/false test

True

### Set Algebra

It allows you to compare two different groups of data (segments) and find out how they overlap or differ.

#### Intersection (&)

In [31]:
segment_a = {1, 2, 3}
segment_b = {3, 4, 5}

In [32]:
# Finds only the elements that appear in both sets.
segment_a.intersection(segment_b)
# or
segment_a & segment_b

{3}

#### Union (|)

In [33]:
# Combines both sets into one, keeping only unique elements.
segment_a.union(segment_b)
# or
segment_a | segment_b

{1, 2, 3, 4, 5}

#### Difference (-)

In [34]:
# elements in A but not in B
segment_a.difference(segment_b)
# or
segment_a - segment_b

{1, 2}

#### Symmetric Difference (^)

In [35]:
# It keeps everything except the ones they have in common.
segment_a.symmetric_difference(segment_b)
# or
segment_a ^ segment_b

{1, 2, 4, 5}

#### Analytical Use Cases

##### Removing Duplicates

In [ ]:
# Converting the list to a set automatically "de-duplicates" the data.
transactions = [101, 102, 102, 103, 104]
unique_transactions = set(transactions)
unique_transactions

{101, 102, 103, 104}

##### Customer Overlap Between Campaigns (Intersection)

In [37]:
campaign_a = {1, 2, 3, 4}
campaign_b = {3, 4, 5, 6}

overlap = campaign_a & campaign_b
overlap

{3, 4}

##### Finding New Customers (Difference)

In [38]:
new_customers = campaign_b - campaign_a
new_customers

{5, 6}

##### Data Validation / Integrity Checks

In [40]:
valid_ids = {1, 2, 3, 4, 5}
incoming_ids = {2, 3, 6}

invalid_ids = incoming_ids - valid_ids
invalid_ids

{6}

6 is flagged as invalid because it doesn't exist in the master list.

#### Limitations

##### No Indexing or Guaranteed Order

In a list, items are like people standing in a line (everyone has a number). 
In a set, items are like balls in a bag; you can check if a ball is in there, but there is no "first" ball.
In a set You cannot write s[0] to get the first item.

##### The "Hashable" Rule

Elements inside a set must be immutable (unchangeable).
To keep membership checking lightning-fast, Python creates a unique "fingerprint" (a hash) for every item. 
If an item can change (like a list can), its fingerprint would change too, and the set would "lose" it.

This will fail
s = {[1, 2], [3, 4]}

In [ ]:
# correct type
s = {(1, 2), (3, 4)}

#### When to Use Sets

* Order doesn't matter: You don't need a "first, second, third" sequence.

* Uniqueness is mandatory: You want to automatically ban duplicates.

* Speed is a priority: You need to check for an item's existence instantly.

* Group Logic: You need to compare two groups (like finding people who are in Group A but not Group B).

##### Sets as a "Mathematical Tool"

shifts the perspective from sets being just "boxes for data" to being "engines for logic." 
Because they are built on mathematical set theory, they enable:

* Efficient Deduplication: Cleaning messy data with one command.
* Group Comparisons: Using Intersection, Union, and Difference to segment audiences.

##### Analytical Real-World Use

where you'll actually see this in a data career:
* Customer Segments: "Show me users who bought a subscription AND a gift card."
* Campaign Overlaps: Measuring how much your Facebook ads and Google ads hit the same people.
* Data Validation: Checking if a list of new IDs contains any "bad" IDs that shouldn't be there.

Think of sets as your go-to structure for “who is in / who is not in” problems.

## Dictionary {}

Dictionary (or dict), is one of the most powerful and frequently used data structures in Python. 
If a list is a numbered sequence of items, a dictionary is a labeled collection of information.
It works just like a real-world dictionary: you look up a Key (the word) to find its Value (the definition).

### Structure: Keys and Values

A dictionary is made of Key-Value pairs.

customer = {"name": "Anna", "revenue": 150, "city": "Yerevan"}
 * "name", "revenue", and "city" are the Keys.
 * "Anna", 150, and "Yerevan" are the Values.

In [3]:
customer = {
    "name": "Anna",
    "revenue": 150,
    "city": "Yerevan"
}

customer

{'name': 'Anna', 'revenue': 150, 'city': 'Yerevan'}

### Core Properties

* Unique Keys: You can't have two keys with the same name (e.g., you can't have two "name" labels for one customer).

* Flexible Values: As you can see, the values can be different types: a string ("Anna"), an integer (150), or even another dictionary!

* Fast Lookup: Like a set, dictionaries are optimized so that finding a value by its key is nearly instantaneous, even with millions of entries.

### How to Use a Dictionary

In [4]:
# Accessing Data
#Instead of using a number index like [0], you use the key name in square brackets:

customer["revenue"]

150

In [5]:
# Adding data 
customer["segment"] = "Premium"
# Updating data
customer["revenue"] = 200
customer

{'name': 'Anna', 'revenue': 200, 'city': 'Yerevan', 'segment': 'Premium'}

In [6]:
# Removing Data
del customer["city"]
customer

{'name': 'Anna', 'revenue': 200, 'segment': 'Premium'}

## From Dictionary to Structured Data

In [7]:
customers = [
    {"name": "Anna", "revenue": 150},
    {"name": "David", "revenue": 220},
    {"name": "Mariam", "revenue": 90}
]

customers

[{'name': 'Anna', 'revenue': 150},
 {'name': 'David', 'revenue': 220},
 {'name': 'Mariam', 'revenue': 90}]

### The Anatomy of Structured Data
Look closely at how the customers variable is built:

* The Outer Layer (The List): Notice the square brackets [ ]. This is a List used to hold a sequence of multiple items.

* The Inner Layer (The Dictionaries): Inside that list, each item is a Dictionary { }. Each dictionary represents one specific row or record (e.g., one person).

### Converting Code to a Table
* The Keys in the dictionaries ("name", "revenue") become the Column Headers.
* The Values ("Anna", 150) become the Cells.
* Each Dictionary in the list becomes a Row.

### Why This Matters: The Path to Pandas
Pandas is the most popular Python library for data analysis. 
When you import a CSV file or an Excel sheet into Python, the computer essentially sees it as a giant version of this "List of Dictionaries."

Key Advantages
Scalability: 
You can easily add a new customer by just adding one more dictionary to the list: customers.append({"name": "Leo", "revenue": 300}).

Searchability: 
You can use a for loop to go through the list and find only customers where revenue > 100.

Organization: 
It keeps related data (like a name and their specific revenue) tied together so they don't get mixed up with other people's data.

## Transition to Pandas

### Creating a DataFrame

DataFrame (df) is essentially a high-powered, programmatic version of an Excel spreadsheet.

In [2]:
import pandas as pd

data = {
    "name": ["Anna", "David", "Mariam"],
    "revenue": [150, 220, 90],
    "city": ["Yerevan", "Tbilisi", "Warsaw"]
}

df = pd.DataFrame(data)
df

     name  revenue     city
0    Anna      150  Yerevan
1   David      220  Tbilisi
2  Mariam       90   Warsaw

Index: The bold numbers on the far left ($0, 1, 2$). These are the row addresses.

### Inspecting Structure (Health Check)

how to peek under the hood to see what your data actually looks like using three essential commands:

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     3 non-null      str
 1   revenue  3 non-null      int64
 2   city     3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

df.info() show how many rows you have (3 entries).

If any data is missing (3 non-null means every cell is filled).

The Dtype (Data Type): You'll see str for text and int64 for whole numbers. This is where your knowledge of Integers and Strings becomes vital!

In [4]:
df.shape

(3, 3)

3 rows and 3 columns.

In [5]:
df.columns

Index(['name', 'revenue', 'city'], dtype='str')

This lists out the names of your headers: ['name', 'revenue', 'city']
and data type

## Basic DataFrame Manipulation

Will help you how to "slice and dice" your data table and how to perform math across entire columns at once.

### Selecting Columns

In a large dataset, you rarely need every single piece of information. Selecting columns allows you to focus on specific features:

Single Column: df["revenue"] extracts just the revenue data. This is often called a Series in Pandas.

In [6]:
df["revenue"]

0    150
1    220
2     90
Name: revenue, dtype: int64

Multiple Columns: df[["name", "revenue"]] extracts a subset of the table. Notice the double square brackets [[ ]].

Tip: The inner brackets are a list of the column names you want, and the outer brackets tell the DataFrame to fetch them.

In [7]:
df[["name", "revenue"]]

     name  revenue
0    Anna      150
1   David      220
2  Mariam       90

### Adding a Column (Feature Engineering)

In [17]:
t = 0.2
df["revenue_after_tax"] = df["revenue"] * (1 - t)
df

     name  revenue     city  revenue_after_tax
0    Anna      150  Yerevan              120.0
1   David      220  Tbilisi              176.0
2  Mariam       90   Warsaw               72.0

### Removing a Column

In [18]:
df.drop("city", axis=1)

     name  revenue  revenue_after_tax
0    Anna      150              120.0
1   David      220              176.0
2  Mariam       90               72.0

axis=1: This is crucial. In Pandas, axis=0 refers to rows, and axis=1 refers to columns. 

By saying axis=1, you are telling the computer, "Find the vertical column named 'city' and remove it."

In [20]:
df = df.drop("city", axis=1)

In [21]:
df

     name  revenue  revenue_after_tax
0    Anna      150              120.0
1   David      220              176.0
2  Mariam       90               72.0

df.drop("city", axis=1)  VS    df = df.drop("city", axis=1)

When you just run df.drop("city", axis=1), Pandas shows you a preview of what the table looks like without that column.

However, it doesn't actually change the original df variable.

If you typed df again right after, the "city" column would still be there!


To actually save your changes, you have to use Reassignment: df = df.drop("city", axis=1)

This tells the computer: "Take the version of the table without the city column and save it over the old version of df."